spring.application.name=PD_Pro_Biblioteka
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=oskar.andrzejewskiv2@gmail.com
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=*
supabase.api.key=${SUPABASE_API_KEY}
supabase.api.key2=${SUPABASE_API_KEY2}
supabase.api.url=${SUPABASE_API_URL}
jwt.key=${JWT_KEY}